// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repository;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.PresidentialCandidateSearchTerm", b =>
                {
                    b.Property<int>("PresidentialCandidateSearchTermId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PresidentialCandidateSearchTermId"));

                    b.Property<string>("CandidateBase64Pic")
                        .HasColumnType("text");

                    b.Property<string>("CandidateSearchTerm")
                        .HasColumnType("text");

                    b.Property<long>("NumberOfNegativeTweets")
                        .HasColumnType("bigint");

                    b.Property<long>("NumberOfNeutralTweets")
                        .HasColumnType("bigint");

                    b.Property<long>("NumberOfPositiveTweets")
                        .HasColumnType("bigint");

                    b.Property<string>("OverAllPublicSentimentOfCandidate")
                        .HasColumnType("text");

                    b.Property<double>("OverAllSentimentProbability")
                        .HasColumnType("double precision");

                    b.Property<long>("TotalNumberOfTweetsAssesed")
                        .HasColumnType("bigint");

                    b.HasKey("PresidentialCandidateSearchTermId");

                    b.ToTable("PresidentialCandidatesSearchTerms");
                });

            modelBuilder.Entity("Entities.Models.Tweet", b =>
                {
                    b.Property<Guid>("TweetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BestClassName")
                        .HasColumnType("text");

                    b.Property<float>("BestClassProbability")
                        .HasColumnType("real");

                    b.Property<int>("PresidentialCandidateSearchTermId")
                        .HasColumnType("integer");

                    b.Property<float>("ProbabilityOfBeingPositive")
                        .HasColumnType("real");

                    b.Property<bool>("SentimentHasBeenPerformed")
                        .HasColumnType("boolean");

                    b.Property<string>("TweetText")
                        .HasColumnType("text");

                    b.HasKey("TweetId");

                    b.HasIndex("PresidentialCandidateSearchTermId");

                    b.ToTable("Opinions");
                });

            modelBuilder.Entity("Entities.Models.Tweet", b =>
                {
                    b.HasOne("Entities.Models.PresidentialCandidateSearchTerm", null)
                        .WithMany("Opinions")
                        .HasForeignKey("PresidentialCandidateSearchTermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.PresidentialCandidateSearchTerm", b =>
                {
                    b.Navigation("Opinions");
                });
#pragma warning restore 612, 618
        }
    }
}
